
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	rotaryCondensentrator = "150"
	#Energy per operation tick (Joules).
	nutritionalLiquifier = "600"
	#Energy per operation tick (Joules).
	digitalMiner = "500"
	#Energy per operation tick (Joules).
	energizedSmelter = "200"
	#Energy per operation tick (Joules).
	pigmentExtractor = "300"
	#Energy per operation tick (Joules).
	seismicVibrator = "150"
	#Energy per operation tick (Joules).
	isotopicCentrifuge = "300"
	#Energy per operation tick (Joules).
	laser = "15000"
	#Energy per operation tick (Joules).
	modificationStation = "300"
	#Energy per operation tick (Joules).
	chemicalInjectionChamber = "800"
	#Energy per operation tick (Joules).
	crusher = "200"
	#Energy per operation tick (Joules).
	pressurizedReactionBase = "25"
	#Energy per operation tick (Joules).
	chemicalInfuser = "400"
	#Energy per operation tick (Joules).
	formulaicAssemblicator = "300"
	#Energy per operation tick (Joules).
	osmiumCompressor = "500"
	#Energy per operation tick (Joules).
	precisionSawmill = "200"
	#Energy per operation tick (Joules).
	paintingMachine = "125"
	#Energy per operation tick (Joules).
	pigmentMixer = "225"
	#Energy per operation tick (Joules).
	antiprotonicNucleosynthesizer = "120000"
	#Energy per operation tick (Joules).
	combiner = "200"
	#Energy per operation tick (Joules).
	metallurgicInfuser = "600"
	#Energy per operation tick (Joules).
	purificationChamber = "300"
	#Energy per operation tick (Joules).
	oxidationChamber = "250"
	#Energy per operation tick (Joules).
	chemicalCrystallizer = "600"
	#Energy per operation tick (Joules).
	fluidicPlenisher = "150"
	#Energy that can be transferred at once per charge operation (Joules).
	chargePad = "1024000"
	#Energy per operation tick (Joules).
	electricPump = "250"
	#Energy per operation tick (Joules).
	enrichmentChamber = "300"
	#Energy per operation tick (Joules).
	chemicalDissolutionChamber = "450"
	#Energy per operation tick (Joules).
	chemicalWasher = "300"

	#Teleporter
	[usage.teleporter]
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = "40"
		#Flat additional cost for interdimensional teleportation.
		teleporterDimensionPenalty = "20000"
		#Base Joules cost for a teleportation.
		teleporterBase = "5000"

